### ISSUE TITLE
Does this works with Mongoid 2.1.7?

### ISSUE THREAD

**Issue by allochi** [mongoid/mongoid-history#13]
I would love to use it, but I followed the instructions and I can't get it to work, I added the class HistoryTracker, and I added the includes, basically I copied an pasted what the instructions show, when I call "source.history_tracks" in console, I get

NoMethodError: undefined method `where' for Object:Class

Could you help please?
